#pragma once

extern Gfx D_80116280[];

#ifdef INTERNAL_SRC_CODE_Z_ACTOR_C
void ActorShadow_DrawCircle(Actor* actor, Lights* lights, GlobalContext* globalCtx);
void ActorShadow_DrawFeet(Actor* actor, Lights* lights, GlobalContext* globalCtx);
void ActorShadow_DrawHorse(Actor* actor, Lights* lights, GlobalContext* globalCtx);
void ActorShadow_DrawWhiteCircle(Actor* actor, Lights* lights, GlobalContext* globalCtx);
void ActorShape_Init(ActorShape* shape, f32 yOffset, ActorShadowFunc shadowDraw, f32 shadowScale);
s32 Actor_ActorAIsFacingActorB(Actor* actorA, Actor* actorB, s16 angle);
s32 Actor_ActorAIsFacingAndNearActorB(Actor* actorA, Actor* actorB, f32 range, s16 angle);
s32 Actor_ActorBIsFacingActorA(Actor* actorA, Actor* actorB, s16 angle);
u8 Actor_ApplyDamage(Actor* actor);
void Actor_ChangeCategory(GlobalContext* globalCtx, ActorContext* actorCtx, Actor* actor, u8 actorCategory);
Actor* Actor_Delete(ActorContext* actorCtx, Actor* actor, GlobalContext* globalCtx);
void Actor_DrawDoorLock(GlobalContext* globalCtx, s32 arg1, s32 arg2);
Actor* Actor_Find(ActorContext* actorCtx, s32 actorId, s32 actorCategory);
Actor* Actor_FindNearby(GlobalContext* globalCtx, Actor* refActor, s16 actorId, u8 actorCategory, f32 range);
Actor* Actor_GetCollidedExplosive(GlobalContext* globalCtx, Collider* collider);
PosRot* Actor_GetFocus(PosRot* arg0, Actor* actor);
Actor* Actor_GetProjectileActor(GlobalContext* globalCtx, Actor* refActor, f32 radius);
void Actor_GetScreenPos(GlobalContext* globalCtx, Actor* actor, s16* x, s16* y);
PosRot* Actor_GetWorld(PosRot* arg0, Actor* actor);
PosRot* Actor_GetWorldPosShapeRot(PosRot* arg0, Actor* actor);
u32 Actor_HasNoParent(Actor* actor, GlobalContext* globalCtx);
u32 Actor_HasParent(Actor* actor, GlobalContext* globalCtx);
f32 Actor_HeightDiff(Actor* actorA, Actor* actorB);
s32 Actor_IsFacingAndNearPlayer(Actor* actor, f32 range, s16 angle);
s32 Actor_IsFacingPlayer(Actor* actor, s16 angle);
s32 Actor_IsMounted(GlobalContext* globalCtx, Actor* horse);
s32 Actor_IsTargeted(GlobalContext* globalCtx, Actor* actor);
void Actor_Kill(Actor* actor);
void Actor_MountHorse(GlobalContext* globalCtx, Player* player, Actor* horse);
void Actor_MoveForward(Actor* actor);
void Actor_Noop(Actor* actor, GlobalContext* globalCtx);
s32 Actor_NotMounted(GlobalContext* globalCtx, Actor* horse);
s32 Actor_OtherIsTargeted(GlobalContext* globalCtx, Actor* actor);
u32 Actor_ProcessTalkRequest(Actor* actor, GlobalContext* globalCtx);
void Actor_SetColorFilter(Actor* actor, s16 colorFlag, s16 colorIntensityMax, s16 xluFlag, s16 duration);
void Actor_SetDropFlag(Actor* actor, ColliderInfo* colBody, s32 freezeFlag);
void Actor_SetDropFlagJntSph(Actor* actor, ColliderJntSph* colBody, s32 freezeFlag);
void Actor_SetFeetPos(Actor* actor, s32 limbIndex, s32 leftFootIndex, Vec3f* leftFootPos, s32 rightFootIndex, Vec3f* rightFootPos);
void Actor_SetFocus(Actor* actor, f32 offset);
void Actor_SetObjectDependency(GlobalContext* globalCtx, Actor* actor);
u32 Actor_SetRideActor(GlobalContext* globalCtx, Actor* horse, s32 arg2);
void Actor_SetScale(Actor* actor, f32 scale);
void Actor_SetTextWithPrefix(GlobalContext* globalCtx, Actor* actor, s16 textIdLower);
Actor* Actor_Spawn(ActorContext* actorCtx, GlobalContext* globalCtx, s16 actorId, f32 posX, f32 posY, f32 posZ, s16 rotX, s16 rotY, s16 rotZ, s16 params);
Actor* Actor_SpawnAsChild(ActorContext* actorCtx, Actor* parent, GlobalContext* globalCtx, s16 actorId, f32 posX, f32 posY, f32 posZ, s16 rotX, s16 rotY, s16 rotZ, s16 params);
Actor* Actor_SpawnEntry(ActorContext* actorCtx, ActorEntry* actorEntry, GlobalContext* globalCtx);
void Actor_SpawnFloorDustRing(GlobalContext* globalCtx, Actor* actor, Vec3f* posXZ, f32 radius, s32 amountMinusOne, f32 randAccelWeight, s16 scale, s16 scaleStep, u8 useLighting);
void Actor_SpawnTransitionActors(GlobalContext* globalCtx, ActorContext* actorCtx);
s16 Actor_TestFloorInDirection(Actor* actor, GlobalContext* globalCtx, f32 distance, s16 angle);
u32 Actor_TextboxIsClosing(Actor* actor, GlobalContext* globalCtx);
void Actor_UpdateAll(GlobalContext* globalCtx, ActorContext* actorCtx);
void Actor_UpdateBgCheckInfo(GlobalContext* globalCtx, Actor* actor, f32 wallCheckHeight, f32 wallCheckRadius, f32 ceilingCheckHeight, s32 flags);
f32 Actor_WorldDistXYZToActor(Actor* actorA, Actor* actorB);
f32 Actor_WorldDistXYZToPoint(Actor* actor, Vec3f* refPoint);
f32 Actor_WorldDistXZToActor(Actor* actorA, Actor* actorB);
f32 Actor_WorldDistXZToPoint(Actor* actor, Vec3f* refPoint);
s16 Actor_WorldPitchTowardActor(Actor* actorA, Actor* actorB);
s16 Actor_WorldPitchTowardPoint(Actor* actor, Vec3f* refPoint);
s16 Actor_WorldYawTowardActor(Actor* actorA, Actor* actorB);
s16 Actor_WorldYawTowardPoint(Actor* actor, Vec3f* refPoint);
void Audio_PlayActorSound2(Actor* actor, u16 sfxId);
void BodyBreak_Alloc(BodyBreak* bodyBreak, s32 count, GlobalContext* globalCtx);
void BodyBreak_SetInfo(BodyBreak* bodyBreak, s32 limbIndex, s32 minLimbIndex, s32 maxLimbIndex, u32 count, Gfx** dList, s16 objectId);
s32 BodyBreak_SpawnParts(Actor* actor, BodyBreak* bodyBreak, GlobalContext* globalCtx, s16 type);
void Enemy_StartFinishingBlow(GlobalContext* globalCtx, Actor* actor);
s32 Flags_GetClear(GlobalContext* globalCtx, s32 flag);
s32 Flags_GetCollectible(GlobalContext* globalCtx, s32 flag);
s32 Flags_GetEventChkInf(s32 flag);
s32 Flags_GetInfTable(s32 flag);
s32 Flags_GetSwitch(GlobalContext* globalCtx, s32 flag);
s32 Flags_GetTempClear(GlobalContext* globalCtx, s32 flag);
s32 Flags_GetTreasure(GlobalContext* globalCtx, s32 flag);
s32 Flags_GetUnknown(GlobalContext* globalCtx, s32 flag);
void Flags_SetClear(GlobalContext* globalCtx, s32 flag);
void Flags_SetCollectible(GlobalContext* globalCtx, s32 flag);
void Flags_SetEventChkInf(s32 flag);
void Flags_SetInfTable(s32 flag);
void Flags_SetSwitch(GlobalContext* globalCtx, s32 flag);
void Flags_SetTempClear(GlobalContext* globalCtx, s32 flag);
void Flags_SetTreasure(GlobalContext* globalCtx, s32 flag);
void Flags_SetUnknown(GlobalContext* globalCtx, s32 flag);
void Flags_UnsetClear(GlobalContext* globalCtx, s32 flag);
void Flags_UnsetSwitch(GlobalContext* globalCtx, s32 flag);
void Flags_UnsetTempClear(GlobalContext* globalCtx, s32 flag);
void Flags_UnsetUnknown(GlobalContext* globalCtx, s32 flag);
f32 Player_GetHeight(Player* player);
s32 Player_IsFacingActor(Actor* actor, s16 angle, GlobalContext* globalCtx);
f32 Rand_CenteredFloat(f32 f);
f32 Rand_ZeroFloat(f32 f);
void TitleCard_InitBossName(GlobalContext* globalCtx, TitleCardContext* titleCtx, void* texture, s16 x, s16 y, u8 width, u8 height);
void TitleCard_InitPlaceName(GlobalContext* globalCtx, TitleCardContext* titleCtx, void* texture, s32 x, s32 y, s32 width, s32 height, s32 delay);
void func_8002BE04(GlobalContext* globalCtx, Vec3f* arg1, Vec3f* arg2, f32* arg3);
void func_8002C124(TargetContext* targetCtx, GlobalContext* globalCtx);
s32 func_8002D53C(GlobalContext* globalCtx, TitleCardContext* titleCtx);
void func_8002D7EC(Actor* actor);
void func_8002D868(Actor* actor);
void func_8002D908(Actor* actor);
void func_8002D97C(Actor* actor);
void func_8002D9A4(Actor* actor, f32 arg1);
void func_8002DBD0(Actor* actor, Vec3f* result, Vec3f* arg2);
f32 func_8002DCE4(Player* player);
s32 func_8002DD6C(Player* player);
s32 func_8002DD78(Player* player);
s32 func_8002DDE4(GlobalContext* globalCtx);
s32 func_8002DDF4(GlobalContext* globalCtx);
void func_8002DE04(GlobalContext* globalCtx, Actor* actorA, Actor* actorB);
void func_8002DE74(GlobalContext* globalCtx, Player* player);
s32 func_8002DEEC(Player* player);
void func_8002DF18(GlobalContext* globalCtx, Player* player);
s32 func_8002DF38(GlobalContext* globalCtx, Actor* actor, u8 csMode);
s32 func_8002DF54(GlobalContext* globalCtx, Actor* actor, u8 arg2);
void func_8002DF90(DynaPolyActor* dynaActor);
void func_8002DFA4(DynaPolyActor* dynaActor, f32 arg1, s16 arg2);
Hilite* func_8002EABC(Vec3f* object, Vec3f* eye, Vec3f* lightDir, GraphicsContext* gfxCtx);
Hilite* func_8002EB44(Vec3f* object, Vec3f* eye, Vec3f* lightDir, GraphicsContext* gfxCtx);
void func_8002EBCC(Actor* actor, GlobalContext* globalCtx, s32 flag);
void func_8002ED80(Actor* actor, GlobalContext* globalCtx, s32 flag);
s32 func_8002F0C8(Actor* actor, Player* player, s32 arg2);
s32 func_8002F1C4(Actor* actor, GlobalContext* globalCtx, f32 arg2, f32 arg3, u32 arg4);
s32 func_8002F298(Actor* actor, GlobalContext* globalCtx, f32 arg2, u32 arg3);
s32 func_8002F2CC(Actor* actor, GlobalContext* globalCtx, f32 arg2);
s32 func_8002F2F4(Actor* actor, GlobalContext* globalCtx);
s8 func_8002F368(GlobalContext* globalCtx);
s32 func_8002F434(Actor* actor, GlobalContext* globalCtx, s32 getItemId, f32 xzRange, f32 yRange);
void func_8002F554(Actor* actor, GlobalContext* globalCtx, s32 getItemId);
void func_8002F580(Actor* actor, GlobalContext* globalCtx);
void func_8002F5C4(Actor* actorA, Actor* actorB, GlobalContext* globalCtx);
void func_8002F5F0(Actor* actor, GlobalContext* globalCtx);
void func_8002F698(GlobalContext* globalCtx, Actor* actor, f32 arg2, s16 arg3, f32 arg4, u32 arg5, u32 arg6);
void func_8002F6D4(GlobalContext* globalCtx, Actor* actor, f32 arg2, s16 arg3, f32 arg4, u32 arg5);
void func_8002F71C(GlobalContext* globalCtx, Actor* actor, f32 arg2, s16 arg3, f32 arg4);
void func_8002F758(GlobalContext* globalCtx, Actor* actor, f32 arg2, s16 arg3, f32 arg4, u32 arg5);
void func_8002F7A0(GlobalContext* globalCtx, Actor* actor, f32 arg2, s16 arg3, f32 arg4);
void func_8002F7DC(Actor* actor, u16 sfxId);
void func_8002F850(GlobalContext* globalCtx, Actor* actor);
void func_8002F8F0(Actor* actor, u16 sfxId);
void func_8002F91C(Actor* actor, u16 sfxId);
void func_8002F948(Actor* actor, u16 sfxId);
void func_8002F974(Actor* actor, u16 sfxId);
void func_8002F994(Actor* actor, s32 arg1);
s32 func_8002F9EC(GlobalContext* globalCtx, Actor* actor, CollisionPoly* poly, s32 bgId, Vec3f* pos);
void func_800304B0(GlobalContext* globalCtx);
void func_800304DC(GlobalContext* globalCtx, ActorContext* actorCtx, ActorEntry* actorEntry);
s32 Actor_IsInUncullZone(GlobalContext* globalCtx, Actor* actorB, Vec3f* projectedPos, f32 projectedW);
void func_800315AC(GlobalContext* globalCtx, ActorContext* actorCtx);
void func_80031A28(GlobalContext* globalCtx, ActorContext* actorCtx);
void func_80031B14(GlobalContext* globalCtx, ActorContext* actorCtx);
void func_80031C3C(ActorContext* actorCtx, GlobalContext* globalCtx);
Actor* func_80032AF0(GlobalContext* globalCtx, ActorContext* actorCtx, Actor** actorPtr, Player* player);
s16 func_80032CB4(s16* arg0, s16 arg1, s16 arg2, s16 arg3);
void func_80033480(GlobalContext* globalCtx, Vec3f* posBase, f32 randRangeDiameter, s32 amountMinusOne, s16 scaleBase, s16 scaleStep, u8 arg6);
Actor* func_80033684(GlobalContext* globalCtx, Actor* explosiveActor);
f32 func_80033AEC(Vec3f* arg0, Vec3f* arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5);
void func_80033C30(Vec3f* arg0, Vec3f* arg1, u8 alpha, GlobalContext* globalCtx);
void func_80033DB8(GlobalContext* globalCtx, s16 arg1, s16 arg2);
void func_80033E1C(GlobalContext* globalCtx, s16 arg1, s16 arg2, s16 arg3);
void func_80033E88(Actor* actor, GlobalContext* globalCtx, s16 arg2, s16 arg3);
void func_8003424C(GlobalContext* globalCtx, Vec3f* arg1);
Hilite* func_800342EC(Vec3f* object, GlobalContext* globalCtx);
Hilite* func_8003435C(Vec3f* object, GlobalContext* globalCtx);
s16 func_800347E8(s16 arg0);
void func_80034A14(Actor* actor, struct_80034A14_arg1* arg1, s16 arg2, s16 arg3);
void func_80034BA0(GlobalContext* globalCtx, SkelAnime* skelAnime, OverrideLimbDraw overrideLimbDraw, PostLimbDraw postLimbDraw, Actor* actor, s16 alpha);
void func_80034CC4(GlobalContext* globalCtx, SkelAnime* skelAnime, OverrideLimbDraw overrideLimbDraw, PostLimbDraw postLimbDraw, Actor* actor, s16 alpha);
s16 func_80034DD4(Actor* actor, GlobalContext* globalCtx, s16 arg2, f32 arg3);
void func_80034EC0(SkelAnime* skelAnime, struct_80034EC0_Entry* animations, s32 index);
void func_80034F54(GlobalContext* globalCtx, s16* arg1, s16* arg2, s32 arg3);
s32 func_800354B4(GlobalContext* globalCtx, Actor* actor, f32 range, s16 arg3, s16 arg4, s16 arg5);
void func_8003555C(GlobalContext* globalCtx, Vec3f* pos, Vec3f* velocity, Vec3f* accel);
void func_800355B8(GlobalContext* globalCtx, Vec3f* pos);
u8 func_800355E4(GlobalContext* globalCtx, Collider* collider);
void func_80035844(Vec3f* arg0, Vec3f* arg1, Vec3s* arg2, s32 arg3);
Actor* func_800358DC(Actor* actor, Vec3f* spawnPos, Vec3s* spawnRot, f32* arg3, s32 timer, s16* unused, GlobalContext* globalCtx, s16 params, s32 arg8);
void func_800359B8(Actor* actor, s16 arg1, Vec3s* arg2);
u16 func_80037C30(GlobalContext* globalCtx, s16 arg1);
s32 func_80037D98(GlobalContext* globalCtx, Actor* actor, s16 arg2, s32* arg3);
s32 func_80038290(GlobalContext* globalCtx, Actor* actor, Vec3s* arg2, Vec3s* arg3, Vec3f arg4);
#else
void ActorShadow_DrawCircle(struct Actor* actor, struct Lights* lights, struct GlobalContext* globalCtx);
void ActorShadow_DrawFeet(struct Actor* actor, struct Lights* lights, struct GlobalContext* globalCtx);
void ActorShadow_DrawHorse(struct Actor* actor, struct Lights* lights, struct GlobalContext* globalCtx);
void ActorShadow_DrawWhiteCircle(struct Actor* actor, struct Lights* lights, struct GlobalContext* globalCtx);
void ActorShape_Init(struct ActorShape* shape, f32 yOffset, ActorShadowFunc shadowDraw, f32 shadowScale);
s32 Actor_ActorAIsFacingActorB(struct Actor* actorA, struct Actor* actorB, s16 angle);
s32 Actor_ActorAIsFacingAndNearActorB(struct Actor* actorA, struct Actor* actorB, f32 range, s16 angle);
s32 Actor_ActorBIsFacingActorA(struct Actor* actorA, struct Actor* actorB, s16 angle);
u8 Actor_ApplyDamage(struct Actor* actor);
void Actor_ChangeCategory(struct GlobalContext* globalCtx, struct ActorContext* actorCtx, struct Actor* actor, u8 actorCategory);
struct Actor* Actor_Delete(struct ActorContext* actorCtx, struct Actor* actor, struct GlobalContext* globalCtx);
void Actor_DrawDoorLock(struct GlobalContext* globalCtx, s32 arg1, s32 arg2);
struct Actor* Actor_Find(struct ActorContext* actorCtx, s32 actorId, s32 actorCategory);
struct Actor* Actor_FindNearby(struct GlobalContext* globalCtx, struct Actor* refActor, s16 actorId, u8 actorCategory, f32 range);
struct Actor* Actor_GetCollidedExplosive(struct GlobalContext* globalCtx, struct Collider* collider);
struct PosRot* Actor_GetFocus(struct PosRot* arg0, struct Actor* actor);
struct Actor* Actor_GetProjectileActor(struct GlobalContext* globalCtx, struct Actor* refActor, f32 radius);
void Actor_GetScreenPos(struct GlobalContext* globalCtx, struct Actor* actor, s16* x, s16* y);
struct PosRot* Actor_GetWorld(struct PosRot* arg0, struct Actor* actor);
struct PosRot* Actor_GetWorldPosShapeRot(struct PosRot* arg0, struct Actor* actor);
u32 Actor_HasNoParent(struct Actor* actor, struct GlobalContext* globalCtx);
u32 Actor_HasParent(struct Actor* actor, struct GlobalContext* globalCtx);
f32 Actor_HeightDiff(struct Actor* actorA, struct Actor* actorB);
s32 Actor_IsFacingAndNearPlayer(struct Actor* actor, f32 range, s16 angle);
s32 Actor_IsFacingPlayer(struct Actor* actor, s16 angle);
s32 Actor_IsMounted(struct GlobalContext* globalCtx, struct Actor* horse);
s32 Actor_IsTargeted(struct GlobalContext* globalCtx, struct Actor* actor);
void Actor_Kill(struct Actor* actor);
void Actor_MountHorse(struct GlobalContext* globalCtx, struct Player* player, struct Actor* horse);
void Actor_MoveForward(struct Actor* actor);
void Actor_Noop(struct Actor* actor, struct GlobalContext* globalCtx);
s32 Actor_NotMounted(struct GlobalContext* globalCtx, struct Actor* horse);
s32 Actor_OtherIsTargeted(struct GlobalContext* globalCtx, struct Actor* actor);
u32 Actor_ProcessTalkRequest(struct Actor* actor, struct GlobalContext* globalCtx);
void Actor_SetColorFilter(struct Actor* actor, s16 colorFlag, s16 colorIntensityMax, s16 xluFlag, s16 duration);
void Actor_SetDropFlag(struct Actor* actor, struct ColliderInfo* colBody, s32 freezeFlag);
void Actor_SetDropFlagJntSph(struct Actor* actor, struct ColliderJntSph* colBody, s32 freezeFlag);
void Actor_SetFeetPos(struct Actor* actor, s32 limbIndex, s32 leftFootIndex, struct Vec3f* leftFootPos, s32 rightFootIndex, struct Vec3f* rightFootPos);
void Actor_SetFocus(struct Actor* actor, f32 offset);
void Actor_SetObjectDependency(struct GlobalContext* globalCtx, struct Actor* actor);
u32 Actor_SetRideActor(struct GlobalContext* globalCtx, struct Actor* horse, s32 arg2);
void Actor_SetScale(struct Actor* actor, f32 scale);
void Actor_SetTextWithPrefix(struct GlobalContext* globalCtx, struct Actor* actor, s16 textIdLower);
struct Actor* Actor_Spawn(struct ActorContext* actorCtx, struct GlobalContext* globalCtx, s16 actorId, f32 posX, f32 posY, f32 posZ, s16 rotX, s16 rotY, s16 rotZ, s16 params);
struct Actor* Actor_SpawnAsChild(struct ActorContext* actorCtx, struct Actor* parent, struct GlobalContext* globalCtx, s16 actorId, f32 posX, f32 posY, f32 posZ, s16 rotX, s16 rotY, s16 rotZ, s16 params);
struct Actor* Actor_SpawnEntry(struct ActorContext* actorCtx, struct ActorEntry* actorEntry, struct GlobalContext* globalCtx);
void Actor_SpawnFloorDustRing(struct GlobalContext* globalCtx, struct Actor* actor, struct Vec3f* posXZ, f32 radius, s32 amountMinusOne, f32 randAccelWeight, s16 scale, s16 scaleStep, u8 useLighting);
void Actor_SpawnTransitionActors(struct GlobalContext* globalCtx, struct ActorContext* actorCtx);
s16 Actor_TestFloorInDirection(struct Actor* actor, struct GlobalContext* globalCtx, f32 distance, s16 angle);
u32 Actor_TextboxIsClosing(struct Actor* actor, struct GlobalContext* globalCtx);
void Actor_UpdateAll(struct GlobalContext* globalCtx, struct ActorContext* actorCtx);
void Actor_UpdateBgCheckInfo(struct GlobalContext* globalCtx, struct Actor* actor, f32 wallCheckHeight, f32 wallCheckRadius, f32 ceilingCheckHeight, s32 flags);
f32 Actor_WorldDistXYZToActor(struct Actor* actorA, struct Actor* actorB);
f32 Actor_WorldDistXYZToPoint(struct Actor* actor, struct Vec3f* refPoint);
f32 Actor_WorldDistXZToActor(struct Actor* actorA, struct Actor* actorB);
f32 Actor_WorldDistXZToPoint(struct Actor* actor, struct Vec3f* refPoint);
s16 Actor_WorldPitchTowardActor(struct Actor* actorA, struct Actor* actorB);
s16 Actor_WorldPitchTowardPoint(struct Actor* actor, struct Vec3f* refPoint);
s16 Actor_WorldYawTowardActor(struct Actor* actorA, struct Actor* actorB);
s16 Actor_WorldYawTowardPoint(struct Actor* actor, struct Vec3f* refPoint);
void Audio_PlayActorSound2(struct Actor* actor, u16 sfxId);
void BodyBreak_Alloc(struct BodyBreak* bodyBreak, s32 count, struct GlobalContext* globalCtx);
void BodyBreak_SetInfo(struct BodyBreak* bodyBreak, s32 limbIndex, s32 minLimbIndex, s32 maxLimbIndex, u32 count, Gfx** dList, s16 objectId);
s32 BodyBreak_SpawnParts(struct Actor* actor, struct BodyBreak* bodyBreak, struct GlobalContext* globalCtx, s16 type);
void Enemy_StartFinishingBlow(struct GlobalContext* globalCtx, struct Actor* actor);
s32 Flags_GetClear(struct GlobalContext* globalCtx, s32 flag);
s32 Flags_GetCollectible(struct GlobalContext* globalCtx, s32 flag);
s32 Flags_GetEventChkInf(s32 flag);
s32 Flags_GetInfTable(s32 flag);
s32 Flags_GetSwitch(struct GlobalContext* globalCtx, s32 flag);
s32 Flags_GetTempClear(struct GlobalContext* globalCtx, s32 flag);
s32 Flags_GetTreasure(struct GlobalContext* globalCtx, s32 flag);
s32 Flags_GetUnknown(struct GlobalContext* globalCtx, s32 flag);
void Flags_SetClear(struct GlobalContext* globalCtx, s32 flag);
void Flags_SetCollectible(struct GlobalContext* globalCtx, s32 flag);
void Flags_SetEventChkInf(s32 flag);
void Flags_SetInfTable(s32 flag);
void Flags_SetSwitch(struct GlobalContext* globalCtx, s32 flag);
void Flags_SetTempClear(struct GlobalContext* globalCtx, s32 flag);
void Flags_SetTreasure(struct GlobalContext* globalCtx, s32 flag);
void Flags_SetUnknown(struct GlobalContext* globalCtx, s32 flag);
void Flags_UnsetClear(struct GlobalContext* globalCtx, s32 flag);
void Flags_UnsetSwitch(struct GlobalContext* globalCtx, s32 flag);
void Flags_UnsetTempClear(struct GlobalContext* globalCtx, s32 flag);
void Flags_UnsetUnknown(struct GlobalContext* globalCtx, s32 flag);
f32 Player_GetHeight(struct Player* player);
s32 Player_IsFacingActor(struct Actor* actor, s16 angle, struct GlobalContext* globalCtx);
f32 Rand_CenteredFloat(f32 f);
f32 Rand_ZeroFloat(f32 f);
void TitleCard_InitBossName(struct GlobalContext* globalCtx, struct TitleCardContext* titleCtx, void* texture, s16 x, s16 y, u8 width, u8 height);
void TitleCard_InitPlaceName(struct GlobalContext* globalCtx, struct TitleCardContext* titleCtx, void* texture, s32 x, s32 y, s32 width, s32 height, s32 delay);
void func_8002BE04(struct GlobalContext* globalCtx, struct Vec3f* arg1, struct Vec3f* arg2, f32* arg3);
void func_8002C124(struct TargetContext* targetCtx, struct GlobalContext* globalCtx);
s32 func_8002D53C(struct GlobalContext* globalCtx, struct TitleCardContext* titleCtx);
void func_8002D7EC(struct Actor* actor);
void func_8002D868(struct Actor* actor);
void func_8002D908(struct Actor* actor);
void func_8002D97C(struct Actor* actor);
void func_8002D9A4(struct Actor* actor, f32 arg1);
void func_8002DBD0(struct Actor* actor, struct Vec3f* result, struct Vec3f* arg2);
f32 func_8002DCE4(struct Player* player);
s32 func_8002DD6C(struct Player* player);
s32 func_8002DD78(struct Player* player);
s32 func_8002DDE4(struct GlobalContext* globalCtx);
s32 func_8002DDF4(struct GlobalContext* globalCtx);
void func_8002DE04(struct GlobalContext* globalCtx, struct Actor* actorA, struct Actor* actorB);
void func_8002DE74(struct GlobalContext* globalCtx, struct Player* player);
s32 func_8002DEEC(struct Player* player);
void func_8002DF18(struct GlobalContext* globalCtx, struct Player* player);
s32 func_8002DF38(struct GlobalContext* globalCtx, struct Actor* actor, u8 csMode);
s32 func_8002DF54(struct GlobalContext* globalCtx, struct Actor* actor, u8 arg2);
void func_8002DF90(struct DynaPolyActor* dynaActor);
void func_8002DFA4(struct DynaPolyActor* dynaActor, f32 arg1, s16 arg2);
Hilite* func_8002EABC(struct Vec3f* object, struct Vec3f* eye, struct Vec3f* lightDir, struct GraphicsContext* gfxCtx);
Hilite* func_8002EB44(struct Vec3f* object, struct Vec3f* eye, struct Vec3f* lightDir, struct GraphicsContext* gfxCtx);
void func_8002EBCC(struct Actor* actor, struct GlobalContext* globalCtx, s32 flag);
void func_8002ED80(struct Actor* actor, struct GlobalContext* globalCtx, s32 flag);
s32 func_8002F0C8(struct Actor* actor, struct Player* player, s32 arg2);
s32 func_8002F1C4(struct Actor* actor, struct GlobalContext* globalCtx, f32 arg2, f32 arg3, u32 arg4);
s32 func_8002F298(struct Actor* actor, struct GlobalContext* globalCtx, f32 arg2, u32 arg3);
s32 func_8002F2CC(struct Actor* actor, struct GlobalContext* globalCtx, f32 arg2);
s32 func_8002F2F4(struct Actor* actor, struct GlobalContext* globalCtx);
s8 func_8002F368(struct GlobalContext* globalCtx);
s32 func_8002F434(struct Actor* actor, struct GlobalContext* globalCtx, s32 getItemId, f32 xzRange, f32 yRange);
void func_8002F554(struct Actor* actor, struct GlobalContext* globalCtx, s32 getItemId);
void func_8002F580(struct Actor* actor, struct GlobalContext* globalCtx);
void func_8002F5C4(struct Actor* actorA, struct Actor* actorB, struct GlobalContext* globalCtx);
void func_8002F5F0(struct Actor* actor, struct GlobalContext* globalCtx);
void func_8002F698(struct GlobalContext* globalCtx, struct Actor* actor, f32 arg2, s16 arg3, f32 arg4, u32 arg5, u32 arg6);
void func_8002F6D4(struct GlobalContext* globalCtx, struct Actor* actor, f32 arg2, s16 arg3, f32 arg4, u32 arg5);
void func_8002F71C(struct GlobalContext* globalCtx, struct Actor* actor, f32 arg2, s16 arg3, f32 arg4);
void func_8002F758(struct GlobalContext* globalCtx, struct Actor* actor, f32 arg2, s16 arg3, f32 arg4, u32 arg5);
void func_8002F7A0(struct GlobalContext* globalCtx, struct Actor* actor, f32 arg2, s16 arg3, f32 arg4);
void func_8002F7DC(struct Actor* actor, u16 sfxId);
void func_8002F850(struct GlobalContext* globalCtx, struct Actor* actor);
void func_8002F8F0(struct Actor* actor, u16 sfxId);
void func_8002F91C(struct Actor* actor, u16 sfxId);
void func_8002F948(struct Actor* actor, u16 sfxId);
void func_8002F974(struct Actor* actor, u16 sfxId);
void func_8002F994(struct Actor* actor, s32 arg1);
s32 func_8002F9EC(struct GlobalContext* globalCtx, struct Actor* actor, CollisionPoly* poly, s32 bgId, struct Vec3f* pos);
void func_800304B0(struct GlobalContext* globalCtx);
void func_800304DC(struct GlobalContext* globalCtx, struct ActorContext* actorCtx, struct ActorEntry* actorEntry);
s32 func_800314D4(struct GlobalContext* globalCtx, struct Actor* actorB, struct Vec3f* arg2, f32 arg3);
void func_800315AC(struct GlobalContext* globalCtx, struct ActorContext* actorCtx);
void func_80031A28(struct GlobalContext* globalCtx, struct ActorContext* actorCtx);
void func_80031B14(struct GlobalContext* globalCtx, struct ActorContext* actorCtx);
void func_80031C3C(struct ActorContext* actorCtx, struct GlobalContext* globalCtx);
struct Actor* func_80032AF0(struct GlobalContext* globalCtx, struct ActorContext* actorCtx, struct Actor** actorPtr, struct Player* player);
s16 func_80032CB4(s16* arg0, s16 arg1, s16 arg2, s16 arg3);
void func_80033480(struct GlobalContext* globalCtx, struct Vec3f* posBase, f32 randRangeDiameter, s32 amountMinusOne, s16 scaleBase, s16 scaleStep, u8 arg6);
struct Actor* func_80033684(struct GlobalContext* globalCtx, struct Actor* explosiveActor);
f32 func_80033AEC(struct Vec3f* arg0, struct Vec3f* arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5);
void func_80033C30(struct Vec3f* arg0, struct Vec3f* arg1, u8 alpha, struct GlobalContext* globalCtx);
void func_80033DB8(struct GlobalContext* globalCtx, s16 arg1, s16 arg2);
void func_80033E1C(struct GlobalContext* globalCtx, s16 arg1, s16 arg2, s16 arg3);
void func_80033E88(struct Actor* actor, struct GlobalContext* globalCtx, s16 arg2, s16 arg3);
void func_8003424C(struct GlobalContext* globalCtx, struct Vec3f* arg1);
Hilite* func_800342EC(struct Vec3f* object, struct GlobalContext* globalCtx);
Hilite* func_8003435C(struct Vec3f* object, struct GlobalContext* globalCtx);
s16 func_800347E8(s16 arg0);
void func_80034A14(struct Actor* actor, struct struct_80034A14_arg1* arg1, s16 arg2, s16 arg3);
void func_80034BA0(struct GlobalContext* globalCtx, struct SkelAnime* skelAnime, OverrideLimbDraw overrideLimbDraw, PostLimbDraw postLimbDraw, struct Actor* actor, s16 alpha);
void func_80034CC4(struct GlobalContext* globalCtx, struct SkelAnime* skelAnime, OverrideLimbDraw overrideLimbDraw, PostLimbDraw postLimbDraw, struct Actor* actor, s16 alpha);
s16 func_80034DD4(struct Actor* actor, struct GlobalContext* globalCtx, s16 arg2, f32 arg3);
void func_80034EC0(struct SkelAnime* skelAnime, struct struct_80034EC0_Entry* animations, s32 index);
void func_80034F54(struct GlobalContext* globalCtx, s16* arg1, s16* arg2, s32 arg3);
s32 func_800354B4(struct GlobalContext* globalCtx, struct Actor* actor, f32 range, s16 arg3, s16 arg4, s16 arg5);
void func_8003555C(struct GlobalContext* globalCtx, struct Vec3f* pos, struct Vec3f* velocity, struct Vec3f* accel);
void func_800355B8(struct GlobalContext* globalCtx, struct Vec3f* pos);
u8 func_800355E4(struct GlobalContext* globalCtx, struct Collider* collider);
void func_80035844(struct Vec3f* arg0, struct Vec3f* arg1, struct Vec3s* arg2, s32 arg3);
struct Actor* func_800358DC(struct Actor* actor, struct Vec3f* spawnPos, struct Vec3s* spawnRot, f32* arg3, s32 timer, s16* unused, struct GlobalContext* globalCtx, s16 params, s32 arg8);
void func_800359B8(struct Actor* actor, s16 arg1, struct Vec3s* arg2);
u16 func_80037C30(struct GlobalContext* globalCtx, s16 arg1);
s32 func_80037D98(struct GlobalContext* globalCtx, struct Actor* actor, s16 arg2, s32* arg3);
s32 func_80038290(struct GlobalContext* globalCtx, struct Actor* actor, struct Vec3s* arg2, struct Vec3s* arg3, struct Vec3f arg4);
#endif
