#pragma once
struct GlobalContext;
struct EnvironmentContext;
struct View;
struct GraphicsContext;
struct Vec3f;
struct LightContext;
struct PauseContext;
struct MessageContext;
struct GameOverContext;
struct SkyboxContext;
struct struct_8011FC1C;
struct LightningStrike;
struct SkyboxFile;

extern u8 D_8011FB34;
extern u8 D_8011FB38;
extern struct_8011FC1C D_8011FC1C[][9];
extern u8 gCustomLensFlareOn;
extern Vec3f gCustomLensFlarePos;
extern f32 gLensFlareColorIntensity;
extern s16 gLensFlareScale;
extern s16 gLensFlareScreenFillAlpha;
extern LightningStrike gLightningStrike;
extern u8 gSkyboxBlendingEnabled;
extern SkyboxFile gSkyboxFiles[];
extern u16 gTimeIncrement;
extern u8 gWeatherMode;

void Environment_AddLightningBolts(GlobalContext* globalCtx, u8 num);
void Environment_AdjustLights(GlobalContext* globalCtx, f32 arg1, f32 arg2, f32 arg3, f32 arg4);
void Environment_ClearBgsDayCount(void);
void Environment_DisableUnderwaterLights(GlobalContext* globalCtx);
void Environment_DrawCustomLensFlare(GlobalContext* globalCtx);
void Environment_DrawLensFlare(GlobalContext* globalCtx, EnvironmentContext* envCtx, View* view, GraphicsContext* gfxCtx, Vec3f pos, s32 unused, s16 arg6, f32 arg7, s16 arg8, u8 arg9);
void Environment_DrawLightning(GlobalContext* globalCtx, s32 unused);
void Environment_DrawRain(GlobalContext* globalCtx, View* view, GraphicsContext* gfxCtx);
void Environment_DrawSandstorm(GlobalContext* globalCtx, u8 sandstormState);
void Environment_DrawSkyboxFilters(GlobalContext* globalCtx);
void Environment_DrawSunAndMoon(GlobalContext* globalCtx);
void Environment_DrawSunLensFlare(GlobalContext* globalCtx, EnvironmentContext* envCtx, View* view, GraphicsContext* gfxCtx, Vec3f pos, s32 unused);
void Environment_EnableUnderwaterLights(GlobalContext* globalCtx, s32 waterLightsIndex);
void Environment_FadeInGameOverLights(GlobalContext* globalCtx);
void Environment_FadeOutGameOverLights(GlobalContext* globalCtx);
void Environment_FillScreen(GraphicsContext* gfxCtx, u8 red, u8 green, u8 blue, u8 alpha, u8 drawFlags);
void Environment_ForcePlaySequence(u16);
s32 Environment_GetBgsDayCount(void);
u16 Environment_GetPixelDepth(s32 x, s32 y);
s32 Environment_GetTotalDays(void);
void Environment_GraphCallback(GraphicsContext* gfxCtx, void* param);
void Environment_Init(GlobalContext* globalCtx, EnvironmentContext* envCtx, s32 unused);
void Environment_InitGameOverLights(GlobalContext* globalCtx);
s32 Environment_IsForcedSequenceDisabled(void);
f32 Environment_LerpWeight(u16 max, u16 min, u16 val);
f32 Environment_LerpWeightAccelDecel(u16 endFrame, u16 startFrame, u16 curFrame, u16 accelDuration, u16 decelDuration);
u8 Environment_SmoothStepToS8(s8* pvalue, s8 target, u8 scale, u8 step, u8 minStep);
u8 Environment_SmoothStepToU8(u8* pvalue, u8 target, u8 scale, u8 step, u8 minStep);
void Environment_Update(GlobalContext* globalCtx, EnvironmentContext* envCtx, LightContext* lightCtx, PauseContext* pauseCtx, MessageContext* msgCtx, GameOverContext* gameOverCtx, GraphicsContext* gfxCtx);
void Environment_UpdateLightningStrike(GlobalContext* globalCtx);
void Environment_UpdateSkybox(u8 skyboxId, EnvironmentContext* envCtx, SkyboxContext* skyboxCtx);
void Environment_WarpSongLeave(GlobalContext* globalCtx);
s32 func_8006F0A0(s32 arg0);
void func_80074CE8(GlobalContext* globalCtx, u32 arg1);
void func_800758AC(GlobalContext* globalCtx);
void func_80077624(GlobalContext* globalCtx);
void func_80077684(GlobalContext* globalCtx);
